# Generated by Django 5.0.4 on 2024-08-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_remove_reservation_room_remove_reservation_user_and_more'),
        ('rooms', '0019_alter_room_google_map_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
