# Generated by Django 5.0.4 on 2024-08-31 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_delete_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_occupancy', models.IntegerField()),
                ('google_map_url', models.URLField(blank=True, max_length=400, null=True, verbose_name='Google Maps URL')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('image2', models.ImageField(default='https:///example.com/default_image.jpg', upload_to='room_images/')),
                ('image3', models.ImageField(default='https://example.com/default_image.jpg', upload_to='room_images/')),
                ('image4', models.ImageField(blank=True, default='https://example.com/default_image.jpg', null=True, upload_to='room_images/')),
                ('image5', models.ImageField(blank=True, default='https://example.com/default_image.jpg', null=True, upload_to='room_images/')),
                ('availability', models.BooleanField(default=True)),
                ('pet_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, to='rooms.amenity')),
                ('bed_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.bedtype')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.location')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype')),
            ],
        ),
    ]
