# Generated by Django 5.0.4 on 2024-08-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image2',
            field=models.ImageField(default='https://example.com/default_image.jpg', upload_to='room_images/'),
        ),
    ]
