# Generated by Django 5.0.4 on 2024-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_rename_image_url_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_content',
            field=models.CharField(default='Banner Content ', max_length=100),
        ),
    ]
